site_name: LIFE OF A TESTER
site_url: https://Giovaaanniii.github.io/Bug-library/
extra:
  homepage: https://Giovaaanniii.github.io/Bug-library/  
  # alternate:
  #   - name: English
  #     link: /en/ 
  #     lang: en
  #   - name: Russian
  #     link: /Bug-library/ru/
  #     lang: ru
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
copyright: >
  Copyright &copy; 2016 - 2024 Martin Donath –
  <a href="#__consent">Change cookie settings</a>  
theme:
  name: material
  features:
    - search
    - search.highlight
    - navigation.instant
    - navigation.instant.prefetch 
    - navigation.expand
    - navigation.indexes
    - navigation.top
    
  logo: static/img/g.png 
  favicon: static/img/g.png
  direction: ltr
  palette:
    
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange      
      accent: deep orange
      font:
        text: Roboto
        code: Roboto Mono
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: deep orange
      font:
        text: Roboto
        code: Roboto Mono
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - css/extra.css
site_author: Ivan Gorbunov
copyright: Giovaaanniii, 2024
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
nav:
  - Welcome!: /Bug-library/
  - Bugs:
    - Running MSS under WAYLAND reveals an error: /Bug-library/mss_under_wayland
